pages = [{"l":"index.html#","e":false,"i":"","n":"Hanafuda","t":"Hanafuda","d":"","k":"static","x":""},
{"l":"view.html#","e":false,"i":"","n":"view","t":"view","d":"","k":"package","x":""},
{"l":"view/ComponentDecoraters$.html#","e":false,"i":"","n":"ComponentDecoraters","t":"ComponentDecoraters","d":"view","k":"object","x":""},
{"l":"view/ComponentDecoraters$$BasicButton.html#","e":false,"i":"","n":"BasicButton","t":"BasicButton(val text: String, action: ActionEvent => Unit) extends UIComponent","d":"view.ComponentDecoraters","k":"class","x":""},
{"l":"view/ComponentDecoraters$$BasicButton.html#text-0","e":false,"i":"","n":"text","t":"text: String","d":"view.ComponentDecoraters.BasicButton","k":"val","x":""},
{"l":"view/ComponentDecoraters$$BasicTextField.html#","e":false,"i":"","n":"BasicTextField","t":"BasicTextField(val prompt: String) extends UIComponent","d":"view.ComponentDecoraters","k":"class","x":""},
{"l":"view/ComponentDecoraters$$BasicTextField.html#prompt-0","e":false,"i":"","n":"prompt","t":"prompt: String","d":"view.ComponentDecoraters.BasicTextField","k":"val","x":""},
{"l":"view/ComponentDecoraters$$HoverEffectDecorator.html#","e":false,"i":"","n":"HoverEffectDecorator","t":"HoverEffectDecorator(component: UIComponent, hoverStyles: Map[String, String]) extends UIComponent","d":"view.ComponentDecoraters","k":"class","x":""},
{"l":"view/ComponentDecoraters$$StyleDecorator.html#","e":false,"i":"","n":"StyleDecorator","t":"StyleDecorator(component: UIComponent, styles: Map[String, String]) extends UIComponent","d":"view.ComponentDecoraters","k":"class","x":""},
{"l":"view/ComponentDecoraters$$UIComponent.html#","e":false,"i":"","n":"UIComponent","t":"UIComponent","d":"view.ComponentDecoraters","k":"trait","x":""},
{"l":"view/ComponentDecoraters$$UIComponent.html#render-d5a","e":false,"i":"","n":"render","t":"render(): Node","d":"view.ComponentDecoraters.UIComponent","k":"def","x":""},
{"l":"view/GUIManager$.html#","e":false,"i":"","n":"GUIManager","t":"GUIManager extends JFXApp3, Observer","d":"view","k":"object","x":""},
{"l":"view/GUIManager$.html#combinationsScene-fffffada","e":false,"i":"","n":"combinationsScene","t":"combinationsScene(gameState: GameState): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#createGameTaskbar-498","e":false,"i":"","n":"createGameTaskbar","t":"createGameTaskbar(gameState: GameState): ToolBar","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#createGameTaskbarButton-3c7","e":false,"i":"","n":"createGameTaskbarButton","t":"createGameTaskbarButton(text: String, action: ActionEvent => Unit): Button","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#createStyledTextField-fffff51f","e":false,"i":"","n":"createStyledTextField","t":"createStyledTextField(textString: String): TextField","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#gameScene-fffffada","e":false,"i":"","n":"gameScene","t":"gameScene(gameState: GameState): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#helpScene-fffffada","e":false,"i":"","n":"helpScene","t":"helpScene(gameState: GameState): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#sceneUninitialized-434","e":false,"i":"","n":"sceneUninitialized","t":"sceneUninitialized(): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#spoilerScene-fffffada","e":false,"i":"","n":"spoilerScene","t":"spoilerScene(gameState: GameState): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/GUIManager$.html#summaryScene-fffffada","e":false,"i":"","n":"summaryScene","t":"summaryScene(gameState: GameState): Scene","d":"view.GUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#","e":false,"i":"","n":"TUIManager","t":"TUIManager extends Observer","d":"view","k":"object","x":""},
{"l":"view/TUIManager$.html#clearScreen-0","e":false,"i":"","n":"clearScreen","t":"clearScreen: String","d":"view.TUIManager","k":"val","x":""},
{"l":"view/TUIManager$.html#colorizeOverviewCard-fffff903","e":false,"i":"","n":"colorizeOverviewCard","t":"colorizeOverviewCard(game: GameState, card: Card): List[String]","d":"view.TUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#printBoard-fffff17f","e":false,"i":"","n":"printBoard","t":"printBoard(game: GameState): String","d":"view.TUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#printHelp-665","e":false,"i":"","n":"printHelp","t":"printHelp(): String","d":"view.TUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#printOverview-fffff17f","e":false,"i":"","n":"printOverview","t":"printOverview(game: GameState): String","d":"view.TUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#printSpoiler-665","e":false,"i":"","n":"printSpoiler","t":"printSpoiler(): String","d":"view.TUIManager","k":"def","x":""},
{"l":"view/TUIManager$.html#printSummary-fffff17f","e":false,"i":"","n":"printSummary","t":"printSummary(game: GameState): String","d":"view.TUIManager","k":"def","x":""},
{"l":"model.html#","e":false,"i":"","n":"model","t":"model","d":"","k":"package","x":""},
{"l":"model.html#containsCard-fffff219","e":false,"i":"","n":"containsCard","t":"containsCard(cards: List[Card], card: Card): Boolean","d":"model","k":"def","x":""},
{"l":"model.html#instantWinCombinations-0","e":false,"i":"","n":"instantWinCombinations","t":"instantWinCombinations: List[Combination]","d":"model","k":"val","x":""},
{"l":"model.html#yakuCombinations-0","e":false,"i":"","n":"yakuCombinations","t":"yakuCombinations: List[Combination]","d":"model","k":"val","x":""},
{"l":"model/AkatanAotanCombination$.html#","e":false,"i":"","n":"AkatanAotanCombination","t":"AkatanAotanCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/AkatanAotanCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.AkatanAotanCombination","k":"val","x":""},
{"l":"model/AkatanAotanCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.AkatanAotanCombination","k":"val","x":""},
{"l":"model/AkatanAotanCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.AkatanAotanCombination","k":"val","x":""},
{"l":"model/AkatanCombination$.html#","e":false,"i":"","n":"AkatanCombination","t":"AkatanCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/AkatanCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.AkatanCombination","k":"val","x":""},
{"l":"model/AkatanCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.AkatanCombination","k":"val","x":""},
{"l":"model/AkatanCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.AkatanCombination","k":"val","x":""},
{"l":"model/AmeShikoCombination$.html#","e":false,"i":"","n":"AmeShikoCombination","t":"AmeShikoCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/AmeShikoCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.AmeShikoCombination","k":"val","x":""},
{"l":"model/AmeShikoCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.AmeShikoCombination","k":"val","x":""},
{"l":"model/AmeShikoCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.AmeShikoCombination","k":"val","x":""},
{"l":"model/AotanCombination$.html#","e":false,"i":"","n":"AotanCombination","t":"AotanCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/AotanCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.AotanCombination","k":"val","x":""},
{"l":"model/AotanCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.AotanCombination","k":"val","x":""},
{"l":"model/AotanCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.AotanCombination","k":"val","x":""},
{"l":"model/Card.html#","e":false,"i":"","n":"Card","t":"Card(month: CardMonth, cardType: CardType, cardName: CardName, grouped: Boolean, index: Int)","d":"model","k":"class","x":""},
{"l":"model/Card.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: List[String]","d":"model.Card","k":"def","x":""},
{"l":"model/CardMonth.html#","e":false,"i":"","n":"CardMonth","t":"CardMonth","d":"model","k":"enum","x":""},
{"l":"model/CardMonth.html#JANUARY-0","e":false,"i":"","n":"JANUARY","t":"JANUARY extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#FEBRUARY-0","e":false,"i":"","n":"FEBRUARY","t":"FEBRUARY extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#MARCH-0","e":false,"i":"","n":"MARCH","t":"MARCH extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#APRIL-0","e":false,"i":"","n":"APRIL","t":"APRIL extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#MAY-0","e":false,"i":"","n":"MAY","t":"MAY extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#JUNE-0","e":false,"i":"","n":"JUNE","t":"JUNE extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#JULY-0","e":false,"i":"","n":"JULY","t":"JULY extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#AUGUST-0","e":false,"i":"","n":"AUGUST","t":"AUGUST extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#SEPTEMBER-0","e":false,"i":"","n":"SEPTEMBER","t":"SEPTEMBER extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#OCTOBER-0","e":false,"i":"","n":"OCTOBER","t":"OCTOBER extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#NOVEMBER-0","e":false,"i":"","n":"NOVEMBER","t":"NOVEMBER extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#DECEMBER-0","e":false,"i":"","n":"DECEMBER","t":"DECEMBER extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardMonth.html#BACK-0","e":false,"i":"","n":"BACK","t":"BACK extends CardMonth","d":"model.CardMonth","k":"val","x":""},
{"l":"model/CardName.html#","e":false,"i":"","n":"CardName","t":"CardName","d":"model","k":"enum","x":""},
{"l":"model/CardName.html#CRANE-0","e":false,"i":"","n":"CRANE","t":"CRANE extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#PLAIN-0","e":false,"i":"","n":"PLAIN","t":"PLAIN extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#NIGHTINGALE-0","e":false,"i":"","n":"NIGHTINGALE","t":"NIGHTINGALE extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#POETRY_TANZAKU-0","e":false,"i":"","n":"POETRY_TANZAKU","t":"POETRY_TANZAKU extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#CURTAIN-0","e":false,"i":"","n":"CURTAIN","t":"CURTAIN extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#CUCKOO-0","e":false,"i":"","n":"CUCKOO","t":"CUCKOO extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#BRIDGE-0","e":false,"i":"","n":"BRIDGE","t":"BRIDGE extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#BUTTERFLIES-0","e":false,"i":"","n":"BUTTERFLIES","t":"BUTTERFLIES extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#BLUE_TANZAKU-0","e":false,"i":"","n":"BLUE_TANZAKU","t":"BLUE_TANZAKU extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#BOAR-0","e":false,"i":"","n":"BOAR","t":"BOAR extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#MOON-0","e":false,"i":"","n":"MOON","t":"MOON extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#GEESE-0","e":false,"i":"","n":"GEESE","t":"GEESE extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#SAKE_CUP-0","e":false,"i":"","n":"SAKE_CUP","t":"SAKE_CUP extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#DEER-0","e":false,"i":"","n":"DEER","t":"DEER extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#RAIN-0","e":false,"i":"","n":"RAIN","t":"RAIN extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#SWALLOW-0","e":false,"i":"","n":"SWALLOW","t":"SWALLOW extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#LIGHTNING-0","e":false,"i":"","n":"LIGHTNING","t":"LIGHTNING extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#PHOENIX-0","e":false,"i":"","n":"PHOENIX","t":"PHOENIX extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardName.html#BACK-0","e":false,"i":"","n":"BACK","t":"BACK extends CardName","d":"model.CardName","k":"val","x":""},
{"l":"model/CardPlant.html#","e":false,"i":"","n":"CardPlant","t":"CardPlant","d":"model","k":"enum","x":""},
{"l":"model/CardPlant.html#Pine-0","e":false,"i":"","n":"Pine","t":"Pine extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Plum-0","e":false,"i":"","n":"Plum","t":"Plum extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Cherry-0","e":false,"i":"","n":"Cherry","t":"Cherry extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Wisteria-0","e":false,"i":"","n":"Wisteria","t":"Wisteria extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Iris-0","e":false,"i":"","n":"Iris","t":"Iris extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Peony-0","e":false,"i":"","n":"Peony","t":"Peony extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Bush_Clover-0","e":false,"i":"","n":"Bush_Clover","t":"Bush_Clover extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Susuki_Grass-0","e":false,"i":"","n":"Susuki_Grass","t":"Susuki_Grass extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Chrysanthemum-0","e":false,"i":"","n":"Chrysanthemum","t":"Chrysanthemum extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Willow-0","e":false,"i":"","n":"Willow","t":"Willow extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardPlant.html#Paulownia-0","e":false,"i":"","n":"Paulownia","t":"Paulownia extends CardPlant","d":"model.CardPlant","k":"val","x":""},
{"l":"model/CardType.html#","e":false,"i":"","n":"CardType","t":"CardType","d":"model","k":"enum","x":""},
{"l":"model/CardType.html#HIKARI-0","e":false,"i":"","n":"HIKARI","t":"HIKARI extends CardType","d":"model.CardType","k":"val","x":""},
{"l":"model/CardType.html#TANE-0","e":false,"i":"","n":"TANE","t":"TANE extends CardType","d":"model.CardType","k":"val","x":""},
{"l":"model/CardType.html#TANZAKU-0","e":false,"i":"","n":"TANZAKU","t":"TANZAKU extends CardType","d":"model.CardType","k":"val","x":""},
{"l":"model/CardType.html#KASU-0","e":false,"i":"","n":"KASU","t":"KASU extends CardType","d":"model.CardType","k":"val","x":""},
{"l":"model/CardType.html#BACK-0","e":false,"i":"","n":"BACK","t":"BACK extends CardType","d":"model.CardType","k":"val","x":""},
{"l":"model/Combination.html#","e":false,"i":"","n":"Combination","t":"Combination","d":"model","k":"trait","x":""},
{"l":"model/Combination.html#evaluate-fffff081","e":false,"i":"","n":"evaluate","t":"evaluate(player: Player): Int","d":"model.Combination","k":"def","x":""},
{"l":"model/Combination.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.Combination","k":"val","x":""},
{"l":"model/Combination.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.Combination","k":"val","x":""},
{"l":"model/Combination.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.Combination","k":"val","x":""},
{"l":"model/Deck.html#","e":false,"i":"","n":"Deck","t":"Deck(cards: List[Card])","d":"model","k":"class","x":""},
{"l":"model/Deck$.html#","e":false,"i":"","n":"Deck","t":"Deck","d":"model","k":"object","x":""},
{"l":"model/Deck$.html#defaultDeck-6e","e":false,"i":"","n":"defaultDeck","t":"defaultDeck(): Deck","d":"model.Deck","k":"def","x":""},
{"l":"model/Deck$.html#poll-fffffaa0","e":false,"i":"","n":"poll","t":"poll(deck: Deck): (Option[Card], Deck)","d":"model.Deck","k":"def","x":""},
{"l":"model/Deck$.html#pollMultiple-fffffc2b","e":false,"i":"","n":"pollMultiple","t":"pollMultiple(deck: Deck, n: Int): (List[Card], Deck)","d":"model.Deck","k":"def","x":""},
{"l":"model/DisplayType.html#","e":false,"i":"","n":"DisplayType","t":"DisplayType","d":"model","k":"enum","x":""},
{"l":"model/DisplayType.html#GAME-0","e":false,"i":"","n":"GAME","t":"GAME extends DisplayType","d":"model.DisplayType","k":"val","x":""},
{"l":"model/DisplayType.html#COMBINATIONS-0","e":false,"i":"","n":"COMBINATIONS","t":"COMBINATIONS extends DisplayType","d":"model.DisplayType","k":"val","x":""},
{"l":"model/DisplayType.html#HELP-0","e":false,"i":"","n":"HELP","t":"HELP extends DisplayType","d":"model.DisplayType","k":"val","x":""},
{"l":"model/DisplayType.html#SPOILER-0","e":false,"i":"","n":"SPOILER","t":"SPOILER extends DisplayType","d":"model.DisplayType","k":"val","x":""},
{"l":"model/DisplayType.html#SUMMARY-0","e":false,"i":"","n":"SUMMARY","t":"SUMMARY extends DisplayType","d":"model.DisplayType","k":"val","x":""},
{"l":"model/GameManager$.html#","e":false,"i":"","n":"GameManager","t":"GameManager","d":"model","k":"object","x":""},
{"l":"model/GameManager$.html#evaluateScore-fffffbe4","e":false,"i":"","n":"evaluateScore","t":"evaluateScore(players: List[Player], multiplierFirst: Int, multiplierSec: Int): (Int, Int)","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#handleKoiKoi-fffff9be","e":false,"i":"","n":"handleKoiKoi","t":"handleKoiKoi(players: List[Player], firstS: Int, secS: Int, board: Deck, deck: Deck, outOfCardsEnding: Boolean): GameStateSummary","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#initializePlayers-944","e":false,"i":"","n":"initializePlayers","t":"initializePlayers(firstPlayer: String, secondPlayer: String, firstScore: Int, secondScore: Int, deck: Deck, customHandFirst: Option[Deck], customHandSec: Option[Deck]): (List[Player], Deck)","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#koiKoiCallHandler-fffff8c0","e":false,"i":"","n":"koiKoiCallHandler","t":"koiKoiCallHandler(game: GameState): GameState","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#koiKoiHandler-fffff8c0","e":false,"i":"","n":"koiKoiHandler","t":"koiKoiHandler(game: GameState): GameState","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#newGame-fffff599","e":false,"i":"","n":"newGame","t":"newGame(firstPlayer: String, secondPlayer: String, firstScore: Int, secondScore: Int, customBoard: Option[List[Card]], customHandFirst: Option[Deck], customHandSec: Option[Deck]): GameState","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameManager$.html#playerHasScoredNewYaku-fffffbba","e":false,"i":"","n":"playerHasScoredNewYaku","t":"playerHasScoredNewYaku(player: Player): Boolean","d":"model.GameManager","k":"def","x":""},
{"l":"model/GameState.html#","e":false,"i":"","n":"GameState","t":"GameState","d":"model","k":"trait","x":""},
{"l":"model/GameState.html#board-0","e":false,"i":"","n":"board","t":"board: Deck","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#deck-0","e":false,"i":"","n":"deck","t":"deck: Deck","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#displayType-0","e":false,"i":"","n":"displayType","t":"displayType: DisplayType","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#handleDiscard-215","e":false,"i":"","n":"handleDiscard","t":"handleDiscard(xS: String): GameState","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#handleMatch-f10","e":false,"i":"","n":"handleMatch","t":"handleMatch(xS: String, yS: String): GameState","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#matchedDeck-0","e":false,"i":"","n":"matchedDeck","t":"matchedDeck: Option[Deck]","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#players-0","e":false,"i":"","n":"players","t":"players: List[Player]","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#queuedCard-0","e":false,"i":"","n":"queuedCard","t":"queuedCard: Option[Card]","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#stderr-0","e":false,"i":"","n":"stderr","t":"stderr: Option[String]","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#stdout-0","e":false,"i":"","n":"stdout","t":"stdout: Option[String]","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#updateGameStateWithDisplayType-a83","e":false,"i":"","n":"updateGameStateWithDisplayType","t":"updateGameStateWithDisplayType(display: DisplayType): GameState","d":"model.GameState","k":"def","x":""},
{"l":"model/GameState.html#updateGameStateWithError-215","e":false,"i":"","n":"updateGameStateWithError","t":"updateGameStateWithError(errorMessage: String): GameState","d":"model.GameState","k":"def","x":""},
{"l":"model/GameStatePendingKoiKoi.html#","e":false,"i":"","n":"GameStatePendingKoiKoi","t":"GameStatePendingKoiKoi(players: List[Player], deck: Deck, board: Deck, displayType: DisplayType, stdout: Option[String], stderr: Option[String]) extends GameState","d":"model","k":"class","x":""},
{"l":"model/GameStatePendingKoiKoi.html#updateGameStateWithDisplayType-a83","e":false,"i":"","n":"updateGameStateWithDisplayType","t":"updateGameStateWithDisplayType(display: DisplayType): GameState","d":"model.GameStatePendingKoiKoi","k":"def","x":""},
{"l":"model/GameStatePendingKoiKoi.html#updateGameStateWithError-215","e":false,"i":"","n":"updateGameStateWithError","t":"updateGameStateWithError(errorMessage: String): GameState","d":"model.GameStatePendingKoiKoi","k":"def","x":""},
{"l":"model/GameStatePlanned.html#","e":false,"i":"","n":"GameStatePlanned","t":"GameStatePlanned(players: List[Player], deck: Deck, board: Deck, displayType: DisplayType, stdout: Option[String], stderr: Option[String]) extends GameState","d":"model","k":"class","x":""},
{"l":"model/GameStatePlanned.html#updateGameStateWithDisplayType-a83","e":false,"i":"","n":"updateGameStateWithDisplayType","t":"updateGameStateWithDisplayType(display: DisplayType): GameState","d":"model.GameStatePlanned","k":"def","x":""},
{"l":"model/GameStatePlanned.html#updateGameStateWithError-215","e":false,"i":"","n":"updateGameStateWithError","t":"updateGameStateWithError(errorMessage: String): GameState","d":"model.GameStatePlanned","k":"def","x":""},
{"l":"model/GameStateRandom.html#","e":false,"i":"","n":"GameStateRandom","t":"GameStateRandom(players: List[Player], deck: Deck, board: Deck, matched: Deck, queued: Card, displayType: DisplayType, stdout: Option[String], stderr: Option[String]) extends GameState","d":"model","k":"class","x":""},
{"l":"model/GameStateRandom.html#updateGameStateWithDisplayType-a83","e":false,"i":"","n":"updateGameStateWithDisplayType","t":"updateGameStateWithDisplayType(display: DisplayType): GameState","d":"model.GameStateRandom","k":"def","x":""},
{"l":"model/GameStateRandom.html#updateGameStateWithError-215","e":false,"i":"","n":"updateGameStateWithError","t":"updateGameStateWithError(errorMessage: String): GameState","d":"model.GameStateRandom","k":"def","x":""},
{"l":"model/GameStateSummary.html#","e":false,"i":"","n":"GameStateSummary","t":"GameStateSummary(players: List[Player], deck: Deck, board: Deck, displayType: DisplayType, stdout: Option[String], stderr: Option[String], outOfCardsEnding: Boolean) extends GameState","d":"model","k":"class","x":""},
{"l":"model/GameStateUninitialized.html#","e":false,"i":"","n":"GameStateUninitialized","t":"GameStateUninitialized(displayType: DisplayType, stderr: Option[String]) extends GameState","d":"model","k":"class","x":""},
{"l":"model/GokoCombination$.html#","e":false,"i":"","n":"GokoCombination","t":"GokoCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/GokoCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.GokoCombination","k":"val","x":""},
{"l":"model/GokoCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.GokoCombination","k":"val","x":""},
{"l":"model/GokoCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.GokoCombination","k":"val","x":""},
{"l":"model/HanamiZakeCombination$.html#","e":false,"i":"","n":"HanamiZakeCombination","t":"HanamiZakeCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/HanamiZakeCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.HanamiZakeCombination","k":"val","x":""},
{"l":"model/HanamiZakeCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.HanamiZakeCombination","k":"val","x":""},
{"l":"model/HanamiZakeCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.HanamiZakeCombination","k":"val","x":""},
{"l":"model/InoshiKachoCombination$.html#","e":false,"i":"","n":"InoshiKachoCombination","t":"InoshiKachoCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/InoshiKachoCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.InoshiKachoCombination","k":"val","x":""},
{"l":"model/InoshiKachoCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.InoshiKachoCombination","k":"val","x":""},
{"l":"model/InoshiKachoCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.InoshiKachoCombination","k":"val","x":""},
{"l":"model/KasuCombination$.html#","e":false,"i":"","n":"KasuCombination","t":"KasuCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/KasuCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.KasuCombination","k":"val","x":""},
{"l":"model/KasuCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.KasuCombination","k":"val","x":""},
{"l":"model/KasuCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.KasuCombination","k":"val","x":""},
{"l":"model/KuttsukiCombination$.html#","e":false,"i":"","n":"KuttsukiCombination","t":"KuttsukiCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/KuttsukiCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.KuttsukiCombination","k":"val","x":""},
{"l":"model/KuttsukiCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.KuttsukiCombination","k":"val","x":""},
{"l":"model/KuttsukiCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.KuttsukiCombination","k":"val","x":""},
{"l":"model/Player.html#","e":false,"i":"","n":"Player","t":"Player(name: String, hand: Deck, side: Deck, score: Int, calledKoiKoi: Boolean, yakusToIgnore: List[Combination])","d":"model","k":"class","x":""},
{"l":"model/SankoCombination$.html#","e":false,"i":"","n":"SankoCombination","t":"SankoCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/SankoCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.SankoCombination","k":"val","x":""},
{"l":"model/SankoCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.SankoCombination","k":"val","x":""},
{"l":"model/SankoCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.SankoCombination","k":"val","x":""},
{"l":"model/ShikoCombination$.html#","e":false,"i":"","n":"ShikoCombination","t":"ShikoCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/ShikoCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.ShikoCombination","k":"val","x":""},
{"l":"model/ShikoCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.ShikoCombination","k":"val","x":""},
{"l":"model/ShikoCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.ShikoCombination","k":"val","x":""},
{"l":"model/TaneCombination$.html#","e":false,"i":"","n":"TaneCombination","t":"TaneCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/TaneCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.TaneCombination","k":"val","x":""},
{"l":"model/TaneCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.TaneCombination","k":"val","x":""},
{"l":"model/TaneCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.TaneCombination","k":"val","x":""},
{"l":"model/TanzakuCombination$.html#","e":false,"i":"","n":"TanzakuCombination","t":"TanzakuCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/TanzakuCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.TanzakuCombination","k":"val","x":""},
{"l":"model/TanzakuCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.TanzakuCombination","k":"val","x":""},
{"l":"model/TanzakuCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.TanzakuCombination","k":"val","x":""},
{"l":"model/TeshiCombination$.html#","e":false,"i":"","n":"TeshiCombination","t":"TeshiCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/TeshiCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.TeshiCombination","k":"val","x":""},
{"l":"model/TeshiCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.TeshiCombination","k":"val","x":""},
{"l":"model/TeshiCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.TeshiCombination","k":"val","x":""},
{"l":"model/TsukimiZakeCombination$.html#","e":false,"i":"","n":"TsukimiZakeCombination","t":"TsukimiZakeCombination extends Combination","d":"model","k":"object","x":""},
{"l":"model/TsukimiZakeCombination$.html#points-0","e":false,"i":"","n":"points","t":"points: Int","d":"model.TsukimiZakeCombination","k":"val","x":""},
{"l":"model/TsukimiZakeCombination$.html#unicode-0","e":false,"i":"","n":"unicode","t":"unicode: String","d":"model.TsukimiZakeCombination","k":"val","x":""},
{"l":"model/TsukimiZakeCombination$.html#unicodeShort-0","e":false,"i":"","n":"unicodeShort","t":"unicodeShort: String","d":"model.TsukimiZakeCombination","k":"val","x":""},
{"l":"controller.html#","e":false,"i":"","n":"controller","t":"controller","d":"","k":"package","x":""},
{"l":"controller/CombinationsCommand.html#","e":false,"i":"","n":"CombinationsCommand","t":"CombinationsCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/Command.html#","e":false,"i":"","n":"Command","t":"Command","d":"controller","k":"trait","x":""},
{"l":"controller/Command.html#execute-fffff74c","e":false,"i":"","n":"execute","t":"execute(currentState: GameState): (GameState, Command)","d":"controller.Command","k":"def","x":""},
{"l":"controller/Command.html#previousState-0","e":false,"i":"","n":"previousState","t":"previousState: Option[GameState]","d":"controller.Command","k":"var","x":""},
{"l":"controller/Command.html#undo-fffff8c0","e":false,"i":"","n":"undo","t":"undo(currentState: GameState): GameState","d":"controller.Command","k":"def","x":""},
{"l":"controller/CommandManager.html#","e":false,"i":"","n":"CommandManager","t":"CommandManager","d":"controller","k":"class","x":""},
{"l":"controller/CommandManager.html#executeCommand-fffff5d9","e":false,"i":"","n":"executeCommand","t":"executeCommand(command: Command, currentState: GameState): GameState","d":"controller.CommandManager","k":"def","x":""},
{"l":"controller/CommandManager.html#redo-fffff8c0","e":false,"i":"","n":"redo","t":"redo(currentState: GameState): GameState","d":"controller.CommandManager","k":"def","x":""},
{"l":"controller/CommandManager.html#undo-fffff8c0","e":false,"i":"","n":"undo","t":"undo(currentState: GameState): GameState","d":"controller.CommandManager","k":"def","x":""},
{"l":"controller/ContinueCommand.html#","e":false,"i":"","n":"ContinueCommand","t":"ContinueCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/DiscardCommand.html#","e":false,"i":"","n":"DiscardCommand","t":"DiscardCommand(xString: String) extends Command","d":"controller","k":"class","x":""},
{"l":"controller/FinishCommand.html#","e":false,"i":"","n":"FinishCommand","t":"FinishCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/GameController$.html#","e":false,"i":"","n":"GameController","t":"GameController extends Observable","d":"controller","k":"object","x":""},
{"l":"controller/GameController$.html#gameState-0","e":false,"i":"","n":"gameState","t":"gameState: GameState","d":"controller.GameController","k":"var","x":""},
{"l":"controller/GameController$.html#processInput-571","e":false,"i":"","n":"processInput","t":"processInput(input: String): Unit","d":"controller.GameController","k":"def","x":""},
{"l":"controller/HelpCommand.html#","e":false,"i":"","n":"HelpCommand","t":"HelpCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/KoiKoiCommand.html#","e":false,"i":"","n":"KoiKoiCommand","t":"KoiKoiCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/MatchCommand.html#","e":false,"i":"","n":"MatchCommand","t":"MatchCommand(xString: String, yString: String) extends Command","d":"controller","k":"class","x":""},
{"l":"controller/NewCommand.html#","e":false,"i":"","n":"NewCommand","t":"NewCommand extends Command","d":"controller","k":"class","x":""},
{"l":"controller/Observable.html#","e":false,"i":"","n":"Observable","t":"Observable","d":"controller","k":"class","x":""},
{"l":"controller/Observable.html#add-fffff454","e":false,"i":"","n":"add","t":"add(s: Observer): Unit","d":"controller.Observable","k":"def","x":""},
{"l":"controller/Observable.html#notifyObservers-ffffffe6","e":false,"i":"","n":"notifyObservers","t":"notifyObservers(gameState: GameState): Unit","d":"controller.Observable","k":"def","x":""},
{"l":"controller/Observable.html#remove-fffff454","e":false,"i":"","n":"remove","t":"remove(s: Observer): Unit","d":"controller.Observable","k":"def","x":""},
{"l":"controller/Observable.html#subscribers-0","e":false,"i":"","n":"subscribers","t":"subscribers: Vector[Observer]","d":"controller.Observable","k":"var","x":""},
{"l":"controller/Observer.html#","e":false,"i":"","n":"Observer","t":"Observer","d":"controller","k":"trait","x":""},
{"l":"controller/Observer.html#update-ffffffe6","e":false,"i":"","n":"update","t":"update(gameState: GameState): Unit","d":"controller.Observer","k":"def","x":""},
{"l":"controller/StartGameCommand.html#","e":false,"i":"","n":"StartGameCommand","t":"StartGameCommand(firstPlayer: String, secondPlayer: String) extends Command","d":"controller","k":"class","x":""},
{"l":"$lessempty$greater$/Hanafuda$.html#","e":false,"i":"","n":"Hanafuda","t":"Hanafuda","d":"","k":"object","x":""},
{"l":"$lessempty$greater$/Hanafuda$.html#main-94c","e":false,"i":"","n":"main","t":"main(): Unit","d":"Hanafuda","k":"def","x":""},
{"l":"$lessempty$greater$/main.html#","e":false,"i":"","n":"main","t":"main","d":"","k":"class","x":""}];