- name: Git checkout (merge)
  uses: actions/checkout@v3
  if: github.event_name != 'pull_request'
  with:
    fetch-depth: 0

- name: Git checkout (PR)
  uses: actions/checkout@v3
  if: github.event_name == 'pull_request'
  with:
    fetch-depth: 0
    ref: ${{ github.event.pull_request.head.sha }}

- name: Run tests
  run: sbt clean coverage test

- name: Upload coverage data to Coveralls
  run: sbt coverageReport coveralls
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}