name: Scala CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: compile
        run: sbt compile
      - name: run tests with coverage
        run: sbt clean coverage test
      - name: aggregate coverage
        run: sbt coverageAggregate
      - name: list coverage data
        run: ls -R target/scala-*/scoverage-data
      - name: generate coverage report
        run: sbt coverageReport
      - name: Upload coverage data to Coveralls
        run: sbt coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}